version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: OME-KABU-WEB-app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - laravel
    tty: true
    stdin_open: true

  web:
    image: nginx:alpine
    container_name: OME-KABU-WEB-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    container_name: OME-KABU-WEB-DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    tty: true
    stdin_open: true

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
